language: python
python:
- '3.6'
before_install:
- sudo apt-get -qq update
install:
- wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n
  '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p}}'
  | xargs wget
- sudo dpkg -i hugo*.deb
- pip install Pygments
- rm -rf public 2> /dev/null
script:
- hugo
- echo 'threechilix.xyz' > public/CNAME
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  email: "$GITHUB_EMAIL"
  name: "$GITHUB_USERNAME"
  verbose: true
  keep-history: true
  local-dir: public
  target_branch: master
  on:
    branch: code
notifications:
  slack:
    rooms:
      secure: NMzKqYc3gSsT/z+SUdO9Qo+XQF0uyXhSb8jWG8vlh7i8I9IAS/Zc8c4GbL2fORM6SihT78+YRZPgJsjRKbOnoarfv7luTR2Aklu03fOu1YnCHAONwKTJ64Lw4SpCHjeyvqEDR26qiVUJhf/G8TkLwc8KnVCpaUjpuPZPnCzna0UiL4viQhMKu86bYlYio27VrxQ30tjpG1Xx+NZsXsZXboTEX8rtwMl4uv0oyk4gCMLwh06yTUCuYAEFRjX01y+PVCwZ7CdVZJofPCALcA61mMUdD2i2fceMzYPUCefenpXBl1V/SqL6OXhpv2oXp3Dxlc65z378CEEAfwmlT3MFo2LQuADdhR05JH1679hLyWy4ex6OMRX06rSo7tZVyCeypFuWy2rkR92sYlfU861vnx5pI9S3QtNc0qOghK7wBML+BNOPCt5Rk5FFT1vuF+IXbu3rSydv1LP4iT+I/vTAOxD3ZARjxULDIcZ0Kgo4BW82JclR4Wem/093YSPNK+FrIGpwlpl1ikWzXj1nEYcauv1Eaj+m2sS27+FMirdD8JGaYuaZWmOQ+bkVIe4ZbDCX2iczWXR42p2rNqbUpG1g8ec72hIMYoDNjs6IgwCeWvHr/JKsR5igg+1CcQEALW/CRxgAAcXmStd7l6aFGtQyUKiOXvwjv1Yx2rbd3Zc9Gk0=
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
    template:
      - "Repo *%{repository_slug}* `%{result}` build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch *%{branch}*."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
