language: python
python:
- '3.6'
before_install:
- sudo apt-get -qq update
install:
- wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n
  '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p}}'
  | xargs wget
- sudo dpkg -i hugo*.deb
- pip install Pygments
- rm -rf public 2> /dev/null
script:
- hugo
- echo 'threechilix.xyz' > public/CNAME
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  email: "$GITHUB_EMAIL"
  name: "$GITHUB_USERNAME"
  verbose: true
  keep-history: true
  local-dir: public
  target_branch: master
  on:
    branch: code
notifications:
  slack:
    rooms:
      secure:
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
    template:
      - "Repo *%{repository_slug}* `%{result}` build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch *%{branch}*."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
