# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/languages/python/
# https://docs.travis-ci.com/user/customizing-the-build/

language: python

python:
    - "3.6"

before_install:
  - sudo apt-get -qq update

# install - install any dependencies required
install:
    # install latest release version
    - wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p}}' | xargs wget
    - sudo dpkg -i hugo*.deb
    - rm -rf public 2> /dev/null

# script - run the build script
script:
  - hugo
  - echo 'threechilix.xyz' > public/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  email: "$GITHUB_EMAIL"
  name: "$GITHUB_USERNAME"
  verbose: true
  keep-history: true
  local-dir: public
  target_branch: master
  on:
    branch: code
    
notifications:
  slack:
    rooms:
      - secure: htZHsjcOEUygac56AcqNkEaURO2+8ifb8JQnuSP8Bnj77SD9gECsg1C1DR9A6qiiFAms9vaJOnXuy9lR7pimqXlpxTetuTEn/oZ4cxjrqUsQw/u06+Un8G/OMmbU+DlHgEIBE+ISSove/WilusjIqJ1ShqfjNNsgl7YfDyuV0CR2l6Z0OReERi0x1jMHPXKBW81JC/+jwuZYLyDTwfCvAd3L+eoNV70BqIjlwim4kBc0bm33aNmKJo+9rsNQMNJBM21s/OUZjzl8um46Qy3FMqA7uUeP+KmMABa985eOuUHUgAae8MYhSZm9zTyZAduLjsSvaBWe4oHNiJqjj6zjSoF6GW+jfrqxKRXn5ndQh/hKfoVj6k6yhF0sGHjjVe6L1cfELlf27L65UoyzQt3lqAuqfPyhRLHdAHfx0bnpjFU3GAWCk/FjV4R0wfvlbMfF3BMIa+IWqckaKJIItwe61Ykf+0HKgIVz7f+z/VyUkCHXUSX/nD7c2bJIeNZjId2rh2tQeQSnNyOFak/5zsp6LgLnRBDIjYv4R5rSz3tcY7JX6kpmESdzldhWIODifLwSzaGBPHFJb2vseKAS/WRiwTfeWoae2yshZ1bYwBbatHeKizR3HzkYfXQnwXwGhNR8J7fvsrP5SccoATqO0qTAU/+fyerbIoRPf4dks2zyU1I=
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
